### ISSUE TITLE
DcCustom package syntax error

### ISSUE THREAD

**Issue by Running-z** [simonfqy/PADME#4]
Do you guarantee that your dcCustom package is OK? I seem to see some grammatical errors:
![image](https://user-images.githubusercontent.com/38971699/44577137-ec045100-a7c2-11e8-830a-69211dbc2f6a.png)

You defined the DAGModel class, but you inherited the DAGTensorGraph class. Do I need to modify these syntax problems?

**Comment by simonfqy** [comment]
Hi, I preserved some models including `DAGModel` from an older version of `DeepChem` package. Because I didn't use them, those inconsistencies do not cause problems for me. I kept them for the possibility of future extensions. Feel free to contribute if you would like to. Currently only a few models are being used and (hopefully) free of bugs, as I indicated in the `Readme` file of the home page.

**Comment by simonfqy** [comment]
Closing the issue for now. Feel free to reopen if necessary.
